name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'k8s/**' # Evita bucles infinitos si solo cambia el YAML

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # ¡CRÍTICO! Permite al bot hacer push de código
      packages: write

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Iniciar sesión en GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extraer metadatos para Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=short

      - name: Construir y subir imagen Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Actualizar manifiesto K8s (GitOps Bridge)
        run: |
          # 1. Extraemos el tag exacto que acabamos de compilar
          SHORT_SHA="sha-${GITHUB_SHA::7}"
          
          # 2. Usamos 'sed' para buscar la línea de la imagen y reemplazarla por la nueva
          sed -i -E "s|image: .*|image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$SHORT_SHA|g" k8s/app.yaml
          
          # 3. Configuramos la identidad del bot de GitHub
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # 4. Hacemos commit y push del cambio. 
          # El [skip ci] en el mensaje evita que el pipeline se vuelva a lanzar en bucle
          git add k8s/app.yaml
          git commit -m "chore(gitops): actualiza tag de imagen a $SHORT_SHA [skip ci]" || echo "No hay cambios para commitear"
          git push